[package]
name = "miniserver"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami = { version = "0.20.0", features = ["rt_tokio"] }
tokio = { version = "1.41.0", features = ["fs", "macros", "rt-multi-thread"] }

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1